/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package avanceproyecto2;
import javax.swing.JOptionPane;
/**
 *
 * @author Colegio
 */
public class VentanaEjercicios extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEjercicios
     */
    public VentanaEjercicios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 2, 18)); // NOI18N
        jLabel1.setText("Ejercicios");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(260, 260, 260))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sentadillas", "Zancadas", "Dominadas", "Peso Muerto", "Crunches con cable", "Fondos en paralelas", "Remo en barra" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Volver al menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trotar", "Subir Escaleras", "Burpees", "Saltos de cuerda" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Flexiones", "Planchas", "Extensiones de triceps", "Elevaciones laterales de hombros" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel2.setText("Elija la opcion que desea");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(25, 25, 25))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addComponent(jButton1)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String ejercicioSeleccionado = (String) jComboBox1.getSelectedItem();
        String nombreEjercicio = "", descripcion = "", repeticiones = "", duracion = "";

        switch (ejercicioSeleccionado) {
            case "Sentadillas":
                nombreEjercicio = "Sentadillas";
                descripcion = "Es un ejercicio que consiste en flexionar las rodillas y bajar el cuerpo hasta quedar en cuclillas.";
                repeticiones = "3 series de 6 a 10 repeticiones, dos veces por semana.";
                duracion = "4 a 10 minutos a la semana.";
                break;
            case "Zancadas":
                nombreEjercicio = "Zancadas";
                descripcion = "La zancada es un ejercicio de fitness para trabajar los músculos de muslos y glúteos.";
                repeticiones = "3 series de 10-12 repeticiones por pierna.";
                duracion = "Entre 5 y 15 segundos por serie.";
                break;
            case "Dominadas":
                nombreEjercicio = "Dominadas";
                descripcion = "Consiste en levantar el cuerpo mientras se está colgado de una barra.";
                repeticiones = "1 a 3 series de 8 a 12 repeticiones.";
                duracion = "2 a 6 minutos aproximadamente por serie.";
                break;
            case "Peso Muerto":
                nombreEjercicio = "Peso Muerto";
                descripcion = "Es un ejercicio de fuerza que consiste en levantar una barra desde el suelo hasta la cintura.";
                repeticiones = "Entre 6 y 12 repeticiones.";
                duracion = "8 a 16 minutos aproximadamente por serie.";
                break;
            case "Crunches con cable":
                nombreEjercicio = "Crunches con cable";
                descripcion = "Los crunches con cable son un ejercicio abdominal realizado con una máquina de polea o cable.";
                repeticiones = "2 o 3 series de 10 a 20 repeticiones.";
                duracion = "2 a 7 minutos por serie.";
                break;
            case "Fondos en paralelas":
                nombreEjercicio = "Fondos en paralelas";
                descripcion = "Ejercicio de fuerza utilizando el peso corporal, ideal para trabajar el pecho y los tríceps.";
                repeticiones = "2 o 3 series de 8 a 12 repeticiones.";
                duracion = "4 a 15 minutos por serie.";
                break;
            case "Remo en barra":
                nombreEjercicio = "Remo en barra";
                descripcion = "Ejercicio de fuerza realizado con una barra que ayuda a desarrollar la espalda, los hombros y los brazos.";
                repeticiones = "8 a 10 repeticiones.";
                duracion = "2.5 a 5 minutos.";
                break;
            default:
                JOptionPane.showMessageDialog(this, "Selección inválida.");
        }
        String informacion = "Nombre del Ejercicio: " + nombreEjercicio + "\n"
                           + "Descripcion: " + descripcion + "\n"
                           + "Numero de Repeticiones: " + repeticiones + "\n"
                           + "Duracion: " + duracion + "\n";
        JOptionPane.showMessageDialog(this, informacion);
    
  
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        String ejercicioSeleccionado = (String) jComboBox3.getSelectedItem();
    String nombreEjercicio = "", descripcion = "", repeticiones = "", duracion = "";

    switch (ejercicioSeleccionado) {
        case "Trotar":
            nombreEjercicio = "Trotar";
            descripcion = "Trotar es un ejercicio cardiovascular ideal para mejorar la resistencia y quemar calorías.";
            repeticiones = "30 minutos a un ritmo moderado, 3-4 veces por semana.";
            duracion = "De 20 a 40 minutos por sesión.";
            break;

        case "Subir escaleras":
            nombreEjercicio = "Subir escaleras";
            descripcion = "Subir escaleras trabaja las piernas, los glúteos y mejora la resistencia.";
            repeticiones = "3 series de 10-15 minutos, 2-3 veces por semana.";
            duracion = "De 15 a 20 minutos por serie.";
            break;

        case "Burpees":
            nombreEjercicio = "Burpees";
            descripcion = "Los burpees son un ejercicio completo de cuerpo que mejora la fuerza y resistencia.";
            repeticiones = "3 series de 10-15 repeticiones.";
            duracion = "2-3 minutos por serie.";
            break;

        case "Saltos de cuerda":
            nombreEjercicio = "Saltos de cuerda";
            descripcion = "El salto de cuerda es un ejercicio cardiovascular excelente para mejorar el ritmo y la agilidad.";
            repeticiones = "3 series de 2-3 minutos.";
            duracion = "De 5 a 10 minutos por sesión.";
            break;

        default:
            JOptionPane.showMessageDialog(this, "Selección inválida.");
            return;
    }

    String informacion = "Nombre del Ejercicio: " + nombreEjercicio + "\n"
                       + "Descripción: " + descripcion + "\n"
                       + "Número de Repeticiones: " + repeticiones + "\n"
                       + "Duración: " + duracion;

    JOptionPane.showMessageDialog(this, informacion);

    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
            String ejercicioSeleccionado = (String) jComboBox4.getSelectedItem();
    String nombreEjercicio = "", descripcion = "", repeticiones = "", duracion = "";

    switch (ejercicioSeleccionado) {
        case "Flexiones":
            nombreEjercicio = "Flexiones";
            descripcion = "Las flexiones son un ejercicio de fuerza que trabaja principalmente el pecho, "
                        + "los hombros y los tríceps.";
            repeticiones = "3 series de 10-15 repeticiones.";
            duracion = "De 5 a 10 minutos por serie.";
            break;

        case "Planchas":
            nombreEjercicio = "Planchas";
            descripcion = "La plancha es un ejercicio de isometría que trabaja todo el core, "
                        + "incluyendo abdominales y espalda baja.";
            repeticiones = "Mantener 30-60 segundos por serie, 3-4 series.";
            duracion = "De 2 a 4 minutos por sesión.";
            break;

        case "Extensiones de triceps":
            nombreEjercicio = "Extensiones de tríceps";
            descripcion = "Las extensiones de tríceps son un ejercicio para trabajar la parte "
                        + "posterior de los brazos.";
            repeticiones = "3 series de 10-12 repeticiones.";
            duracion = "De 3 a 5 minutos por serie.";
            break;

        case "Elevaciones laterales de hombros":
            nombreEjercicio = "Elevaciones laterales de hombros";
            descripcion = "Las elevaciones laterales son un ejercicio de aislamiento para trabajar los hombros.";
            repeticiones = "3 series de 10-15 repeticiones.";
            duracion = "De 3 a 6 minutos por serie.";
            break;

        default:
            JOptionPane.showMessageDialog(this, "Selección inválida.");
            return;
    }

    String informacion = "Nombre del Ejercicio: " + nombreEjercicio + "\n"
                       + "Descripción: " + descripcion + "\n"
                       + "Número de Repeticiones: " + repeticiones + "\n"
                       + "Duración: " + duracion;

    JOptionPane.showMessageDialog(this, informacion);

    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEjercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEjercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEjercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEjercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEjercicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
